# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Users:
            algorithm: bcrypt
        Savage\AuthBundle\Security\User\UserForProvider:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        users:
            entity:
                class:    AppBundle:Users
                property: username
        jaime.users:
            id : jaime.user.provider

    firewalls:
        appanel_login:
            pattern:    ^/appanel/login
            security:   false
        upload_avatar:
            pattern:    ^/appanel/uploadAvatar
            security:   false

        appanel_secured_area:
            pattern: /appanel/*
            form_login:
                check_path: /appanel/check_login
                login_path: /appanel/login
                default_target_path: /appanel/
            logout:
                path: /appanel/logout
                target: /appanel/login
            provider: jaime.users
